### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by Richard-Masefield** [sadekd/nova-opening-hours-field#2]
Hi, thanks for a great looking plugin. 
- How do I create new operating hours if the current data entry under operating_hours is null? 
- The Spatie plugin also allows for 'exceptions', would it be easy enough to add them here?
- If I manually input json content as per the Spatie example, I can see the fields in Nova as per your screenshot, but changing the entry does not save / persist to the database. Is this step missing from your plugin?
Thanks!

**Comment by sadekd** [comment]
Fixed in new release, exceptions still not supported
