### ISSUE TITLE
Bug: Danger Button not rendering in Nova 4

### ISSUE THREAD

**Issue by michaelklopf** [sadekd/nova-opening-hours-field#35]
See the PR by @dmason30 here for a fix https://github.com/sadekd/nova-opening-hours-field/pull/34

We upgraded form Nova 3 to 4 and the danger button is not rendering anymore

<img width="951" alt="image" src="https://github.com/sadekd/nova-opening-hours-field/assets/2892138/b1f2416a-7da7-437d-99bb-ea093f1ddc9f">

**Comment by timdiels1** [comment]
I can confirm the PR is working for Laravel Nova 4.32.12

**Comment by sadekd** [comment]
Merged as v3.0.6, thanks
