### ISSUE TITLE
Are you planning to maintain this repository?

### ISSUE THREAD

**Issue by rreynier** [sadekd/nova-opening-hours-field#6]
I really like this library, but I would really like to see exceptions added. If interested, I could implement this with a PR if you plan to maintain this actively.  Cheers!

**Comment by sadekd** [comment]
PR is welcome, of course :wink:

**Comment by sadekd** [comment]
https://github.com/sadekd/nova-opening-hours-field/pull/18

**Comment by rreynier** [comment]
Awesome, thank you!
